<#
.SYNOPSIS
    WISP Edge — quick SOURCE-based installer for Windows.

.DESCRIPTION
    No compiled/signed release exists yet (CLAUDE.md roadmap item 5 — fleet update
    signing's "last mile" is still open, central doesn't even serve /dl). This is a
    stopgap, not the officially signed fleet path (that's install-edge.ps1, once real
    release binaries + Authenticode signing exist): it git-clones the source, builds a
    venv, and runs the agent straight from Python under a Scheduled Task. There is no
    sha256/signature verification here — integrity comes only from git's own HTTPS
    transport (GitHub TLS + repo history), not a checksum manifest.

    Installs source + venv under C:\WISP\src-repo, identity/config under
    ProgramData\WISP (never touched by a re-run), registers a Scheduled Task that runs
    as SYSTEM at startup with auto-restart (same shape as install-edge.ps1's task, just
    launching python instead of a frozen exe).

.PARAMETER Central
    Central base URL, e.g. https://hansanet.in

.PARAMETER Token
    The self-service node token from central's dashboard (Edge Nodes tab).

.PARAMETER Org
    Org/org id this edge belongs to, e.g. byreddy

.PARAMETER Node
    This edge's node id (defaults to hostname)

.PARAMETER RepoUrl
    Git URL of the wisp source.

.PARAMETER Branch
    Branch to check out.

.EXAMPLE
    One-liner (fetch + run with args in one shot), from an admin PowerShell:

    & ([scriptblock]::Create((irm https://hansanet.in/install-edge-src.ps1))) `
        -Central https://hansanet.in -Token <TOKEN> -Org byreddy -Node byreddy-edge-1
#>
#Requires -RunAsAdministrator
param(
    [Parameter(Mandatory)][string]$Central,
    [Parameter(Mandatory)][string]$Token,
    [string]$Org = "default",
    [string]$Node = $env:COMPUTERNAME,
    [string]$RepoUrl = "https://github.com/haneeshbyreddy/ping_tool.git",
    [string]$Branch = "main"
)

$ErrorActionPreference = 'Stop'

function Log { param([string]$m) Write-Host "> $m" -ForegroundColor Cyan }
function Ok  { param([string]$m) Write-Host "OK $m" -ForegroundColor Green }
function Die { param([string]$m) Write-Host "X  $m" -ForegroundColor Red; exit 1 }

$InstallDir = "C:\WISP"
$RepoDir    = Join-Path $InstallDir "src-repo"
$ConfigDir  = Join-Path $env:ProgramData "WISP"
$TaskName   = "WISP-Edge-Source"

function Ensure-Tool {
    param([string]$Cmd, [string]$WingetId, [string]$FriendlyName)
    if (Get-Command $Cmd -ErrorAction SilentlyContinue) { return }
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        Log "$FriendlyName not found — installing via winget..."
        winget install --id $WingetId -e --silent --accept-package-agreements --accept-source-agreements
        # winget doesn't refresh the current session's PATH; re-import from machine+user scope.
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + `
                    [System.Environment]::GetEnvironmentVariable("Path","User")
    }
    if (-not (Get-Command $Cmd -ErrorAction SilentlyContinue)) {
        Die "$FriendlyName still not on PATH — install it manually, then re-run this script."
    }
    Ok "$FriendlyName installed"
}

Ensure-Tool -Cmd git    -WingetId "Git.Git"            -FriendlyName "Git"
Ensure-Tool -Cmd python -WingetId "Python.Python.3.12" -FriendlyName "Python"

New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null

if (Test-Path (Join-Path $RepoDir ".git")) {
    Log "repo exists, pulling latest $Branch..."
    Push-Location $RepoDir
    git fetch origin $Branch
    git reset --hard "origin/$Branch"
    Pop-Location
} else {
    Log "cloning $RepoUrl ($Branch)..."
    git clone --branch $Branch --depth 1 $RepoUrl $RepoDir
}
Ok "source at $RepoDir"

Log "setting up venv + installing deps (icmplib/httpx/pysnmp)..."
python -m venv (Join-Path $RepoDir ".venv")
& (Join-Path $RepoDir ".venv\Scripts\pip.exe") install -q -r (Join-Path $RepoDir "requirements.txt")
Ok "deps installed"

$envFile = Join-Path $ConfigDir "edge.env.ps1"
Log "writing $envFile (identity + central config)..."
@"
# GENERATED by install-edge-src.ps1 — edit values, not structure. A re-run/update
# only touches the source checkout + venv, never this file.
`$env:WISP_CENTRAL_BRAIN = '1'
`$env:WISP_CENTRAL_URL = '$Central'
`$env:WISP_CENTRAL_TOKEN = '$Token'
`$env:WISP_ORG_ID = '$Org'
`$env:WISP_NODE_ID = '$Node'
"@ | Set-Content -Path $envFile -Encoding ASCII
Ok "wrote identity/config"

$launcher = Join-Path $ConfigDir "run-edge.cmd"
@"
@echo off
rem GENERATED by install-edge-src.ps1 — runs the agent directly from source (dev/quick
rem install path, not the signed fleet binary). Edit %ProgramData%\WISP\edge.env.ps1
rem for connection settings; re-run install-edge-src.ps1 to pull source updates.
powershell -NoProfile -ExecutionPolicy Bypass -Command ". '$envFile'; & '$RepoDir\.venv\Scripts\python.exe' '$RepoDir\apps\daemon\main.py'"
"@ | Set-Content -Path $launcher -Encoding ASCII

Log "registering scheduled task (runs as SYSTEM, starts at boot, restarts on crash)..."
$principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
$trigger   = New-ScheduledTaskTrigger -AtStartup
$settings  = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew `
    -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero)

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}
$action = New-ScheduledTaskAction -Execute $launcher -WorkingDirectory $RepoDir
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings -Description 'WISP edge (source path, quick install)' -Force | Out-Null
Start-ScheduledTask -TaskName $TaskName

Write-Host ''
Ok "WISP edge (source path) installed and started. Node $Org/$Node -> $Central."
Write-Host "  status: Get-ScheduledTask $TaskName | Get-ScheduledTaskInfo"
Write-Host "  logs:   run '$launcher' by hand in a console to see live output"
Write-Host "  stop:   Stop-ScheduledTask -TaskName $TaskName"
