[CmdletBinding()]
param(
    [switch]$Register,
    [switch]$Unregister,
    [string]$Prefix,
    [string]$Central = '',
    [string]$Token = '',
    [string]$Org = 'default',
    [string]$Node = $env:COMPUTERNAME
)

$ErrorActionPreference = 'Stop'
$TaskName  = 'WISP-Edge'
$ConfigDir = Join-Path $env:ProgramData 'WISP'
$LogDir    = Join-Path $ConfigDir 'logs'

if ($Unregister) {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    }
    exit 0
}

if (-not $Register) { throw 'pass -Register or -Unregister' }
if (-not $Prefix)   { throw '-Prefix (the bin directory) is required with -Register' }

New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null
New-Item -ItemType Directory -Path $LogDir -Force | Out-Null
Start-Transcript -Path (Join-Path $ConfigDir 'install.log') -Append -Force
try {

if ($Central -and $Central -notmatch '^[A-Za-z][A-Za-z0-9+.-]*://') {
    $Central = "https://$Central"
    Write-Output "normalized Central URL to $Central"
}

$envFile = Join-Path $ConfigDir 'edge.env.ps1'
if ($Central -or -not (Test-Path $envFile)) {
    @"
# GENERATED by the WISP Edge installer — edit values, not structure.
# An update never overwrites this file; re-running the installer with a
# Central URL rewrites it.
`$env:WISP_CENTRAL_URL = '$Central'
`$env:WISP_CENTRAL_TOKEN = '$Token'
`$env:WISP_ORG_ID = '$Org'
`$env:WISP_NODE_ID = '$Node'
`$env:WISP_AGENT_BIN = '$Prefix\wisp-edge.exe'
`$env:WISP_DB = '$ConfigDir\wisp.db'
"@ | Set-Content -Path $envFile -Encoding ASCII
    Write-Output "wrote $envFile (central=$Central org=$Org node=$Node)"
} else {
    Write-Output "kept existing $envFile (no -Central passed)"
}

$launcher = Join-Path $Prefix 'run-supervisor.cmd'
@"
@echo off
rem GENERATED by the WISP Edge installer — runs the supervisor, which owns the agent's
rem lifecycle and self-update. Edit %ProgramData%\WISP\edge.env.ps1 for connection
rem settings; logs land in %ProgramData%\WISP\logs\edge.log.
if not exist "$LogDir" mkdir "$LogDir"
if exist "$LogDir\edge.log" for %%A in ("$LogDir\edge.log") do if %%~zA gtr 5242880 (
  del /f /q "$LogDir\edge.log.old" 2>nul
  move /y "$LogDir\edge.log" "$LogDir\edge.log.old" >nul
)
powershell -NoProfile -ExecutionPolicy Bypass -Command ". '$envFile'; & '$Prefix\wisp-supervisor.exe'" >> "$LogDir\edge.log" 2>&1
"@ | Set-Content -Path $launcher -Encoding ASCII

$principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
$trigger   = New-ScheduledTaskTrigger -AtStartup
$settings  = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew `
    -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero)
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
}
$action = New-ScheduledTaskAction -Execute $launcher -WorkingDirectory $Prefix
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings `
    -Description 'WISP edge supervisor (launches + self-updates the agent)' -Force | Out-Null
Write-Output "registered scheduled task $TaskName"

if (-not ((Get-Content $envFile -Raw) -match "WISP_CENTRAL_URL = 'https?://")) {
    Write-Warning 'no central URL configured; task registered but not started'
    exit 10
}

$statusFile = Join-Path $ConfigDir 'status.json'
$startedAt  = Get-Date
Start-ScheduledTask -TaskName $TaskName
$deadline = $startedAt.AddSeconds(30)
while ((Get-Date) -lt $deadline) {
    if ((Test-Path $statusFile) -and ((Get-Item $statusFile).LastWriteTime -gt $startedAt)) {
        Write-Output ("probe is up: " + (Get-Content $statusFile -Raw))
        exit 0
    }
    Start-Sleep -Seconds 1
}
Write-Warning ("task started but the probe wrote no status within 30s. Check " +
    "$LogDir\edge.log, Task Scheduler (task '$TaskName' last run result), and " +
    "Windows Security > Protection history (unsigned binaries get quarantined).")
exit 10

} finally {
    Stop-Transcript | Out-Null
}
