"""Route tables for central's HTTP handler.

``server.py`` owns transport, auth plumbing and the edge-ingest special cases;
everything routable by exact path lives here. GET handlers are called as
``fn(h, qs)``; dashboard POST handlers as ``fn(h, user, body)`` after the
session check (and with AuthError/InventoryError mapped to 422 by the caller).
"""
from __future__ import annotations

from wisp.central.api import devices, edge, fleet, orgs, outages, proxy, users

GET = {
    "/healthz": orgs.healthz,
    "/api/me": orgs.me,
    "/api/summary": outages.summary,
    "/api/system": orgs.system,
    "/api/admin/overview": orgs.admin_overview,
    "/api/admin/settings": orgs.admin_settings,
    "/api/billing": orgs.billing,
    "/api/events": outages.events,
    "/edge/devices": edge.devices,
    "/api/orgs": orgs.list_orgs,
    "/api/users": users.list_users,
    "/api/nodes": fleet.nodes,
    "/api/inventory": devices.list_devices,
    "/api/regions": devices.regions,
    "/api/inventory/routes": devices.routes,
    "/api/inventory/ports": devices.ports,
    "/api/inventory/link-ports": devices.link_ports,
    "/api/inventory/optics": devices.optics,
    "/api/inventory/onu-search": devices.onu_search,
    "/api/inventory/snmp-walks": devices.snmp_walks,
    "/api/inventory/snmp-walk/result": devices.snmp_walk_result,
    "/api/snmp-profiles": devices.snmp_profiles,
    "/api/gpon-profiles": devices.gpon_profiles,
    "/api/web-optics-profiles": devices.web_optics_profiles,
    "/api/inventory/snmp-status": devices.snmp_status,
    "/api/inventory/rx-status": devices.rx_status,
    "/api/inventory/credentials": devices.webui_credentials,
    "/api/inventory/redundancy": devices.redundancy,
    "/api/inventory/perf": devices.perf,
    "/api/inventory/perf/samples": devices.perf_samples,
    "/api/pon/faults": outages.pon_faults,
    "/api/pon/summary": outages.pon_summary,
    "/api/incident/shape": outages.incident_shape,
    "/api/analytics": outages.analytics,
    "/api/analytics/trend": outages.analytics_trend,
    "/api/outages": outages.list_open,
    "/api/logs": outages.logs,
    "/api/proxy/sessions": proxy.sessions_list,
    "/api/proxy/audit": proxy.audit_list,
}

POST = {
    "/api/orgs": orgs.create,
    "/api/orgs/delete": orgs.delete,
    "/api/org": orgs.update,
    "/api/admin/settings": orgs.admin_settings_write,
    "/api/admin/billing": orgs.admin_billing_write,
    "/api/billing/paid": orgs.billing_paid,
    "/api/billing/plan": orgs.billing_plan,
    "/api/test-alert": orgs.test_alert,
    "/api/users": users.create,
    "/api/users/deactivate": users.deactivate,
    "/api/users/delete": users.delete,
    "/api/users/password": users.password,
    "/api/users/whatsapp": users.whatsapp,
    "/api/users/totp/start": users.totp_start,
    "/api/users/totp/confirm": users.totp_confirm,
    "/api/users/totp/disable": users.totp_disable,
    "/api/users/totp/recovery": users.totp_regenerate,
    "/api/nodes": fleet.register,
    "/api/nodes/rotate": fleet.rotate,
    "/api/nodes/revoke": fleet.revoke,
    "/api/nodes/delete": fleet.delete,
    "/api/nodes/update": fleet.update,
    "/api/nodes/restart": fleet.restart,
    "/api/nodes/color": fleet.color,
    "/api/inventory": devices.create,
    "/api/inventory/update": devices.update,
    "/api/inventory/delete": devices.delete,
    "/api/inventory/maintenance": devices.maintenance,
    "/api/inventory/tree-detached": devices.tree_detached,
    "/api/inventory/tag-color": devices.tag_color,
    "/api/inventory/location": devices.location,
    "/api/inventory/route": devices.route,
    "/api/inventory/link-style": devices.link_style,
    "/api/inventory/snmp": devices.snmp,
    "/api/inventory/web-access": devices.web_access,
    "/api/inventory/capability": devices.capability,
    "/api/inventory/credentials": devices.webui_credentials_set,
    "/api/inventory/credentials/clear": devices.webui_credentials_clear,
    "/api/inventory/snmp-walk": devices.snmp_walk_create,
    "/api/snmp-profiles": devices.profile_create,
    "/api/snmp-profiles/update": devices.profile_update,
    "/api/snmp-profiles/delete": devices.profile_delete,
    "/api/gpon-profiles": devices.gpon_profile_create,
    "/api/gpon-profiles/update": devices.gpon_profile_update,
    "/api/gpon-profiles/delete": devices.gpon_profile_delete,
    "/api/web-optics-profiles": devices.web_optics_profile_create,
    "/api/web-optics-profiles/update": devices.web_optics_profile_update,
    "/api/web-optics-profiles/delete": devices.web_optics_profile_delete,
    "/api/inventory/ports/monitored": devices.port_monitored,
    "/api/inventory/ports/feeds": devices.port_feeds,
    "/api/inventory/ports/uplink": devices.port_uplink,
    "/api/inventory/ports/bandwidth": devices.port_bandwidth,
    "/api/inventory/optics/ack": devices.optics_ack,
    "/api/inventory/optics/thresholds": devices.optics_thresholds,
    "/api/inventory/rx-refresh": devices.rx_refresh,
    "/api/inventory/links": devices.link_add,
    "/api/inventory/links/delete": devices.link_delete,
    "/api/inventory/peers": devices.peer_add,
    "/api/inventory/peers/delete": devices.peer_delete,
    "/api/regions": devices.region_add,
    "/api/regions/rename": devices.region_rename,
    "/api/regions/delete": devices.region_delete,
    "/api/proxy/session": proxy.session_create,
    "/api/proxy/close": proxy.session_close,
    "/api/outages/acknowledge": outages.acknowledge,
    "/api/outages/postmortem": outages.postmortem,
    "/api/outages/clear-postmortems": outages.clear_postmortems,
}
